#!/usr/bin/env node
/**
 * bake-glyphs.mjs — DEV-TIME ONLY. Not called by the skill at runtime.
 *
 * Extracts IBM Plex glyph outlines into assets/glyphs.json so that icongen.mjs
 * can render monograms as <path> data with no font files and no font library.
 *
 * Run it only when you need to change the baked charset or add a face:
 *
 *   npm install --no-save opentype.js @ibm/plex-serif @ibm/plex-sans @ibm/plex-mono
 *   node scripts/bake-glyphs.mjs
 *
 * Outlines are emitted in font units (unitsPerEm), y-down, baseline at y=0,
 * which is what opentype.js produces and what icongen.mjs expects.
 */

import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "assets", "glyphs.json");

const CHARSET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
  "abcdefghijklmnopqrstuvwxyz" +
  "0123456789" +
  "&@#+-.!?*<>/";

const FACES = [
  {
    id: "serif-italic",
    label: "IBM Plex Serif Italic 400",
    pkg: "@ibm/plex-serif",
    file: "IBMPlexSerif-Italic.woff",
  },
  {
    id: "sans-medium",
    label: "IBM Plex Sans Medium 500",
    pkg: "@ibm/plex-sans",
    file: "IBMPlexSans-Medium.woff",
  },
  {
    id: "mono",
    label: "IBM Plex Mono Regular 400",
    pkg: "@ibm/plex-mono",
    file: "IBMPlexMono-Regular.woff",
  },
];

function fontPath(face) {
  const pkgJson = require.resolve(`${face.pkg}/package.json`);
  return path.join(path.dirname(pkgJson), "fonts", "complete", "woff", face.file);
}

async function main() {
  const { default: opentype } = await import("opentype.js");

  const out = {
    version: 1,
    note:
      "Outlines in font units, y-down, baseline at y=0. Generated by scripts/bake-glyphs.mjs.",
    source: "IBM Plex (SIL Open Font License 1.1) — see assets/OFL.txt",
    charset: CHARSET,
    faces: {},
  };

  for (const face of FACES) {
    const file = fontPath(face);
    const buf = fs.readFileSync(file);
    const font = opentype.parse(
      buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
    );

    const upm = font.unitsPerEm;
    const glyphs = {};
    const present = [];

    for (const ch of CHARSET) {
      const glyph = font.charToGlyph(ch);
      if (!glyph || glyph.index === 0) {
        console.warn(`  ! ${face.id}: no glyph for ${JSON.stringify(ch)}`);
        continue;
      }
      // fontSize = upm keeps coordinates in font units; baseline lands at y=0.
      const d = glyph.getPath(0, 0, upm).toPathData(1);
      glyphs[ch] = { a: Math.round(glyph.advanceWidth), d };
      present.push(ch);
    }

    // Only non-zero kern pairs within the baked charset.
    const kern = {};
    for (const a of present) {
      const ga = font.charToGlyph(a);
      for (const b of present) {
        const gb = font.charToGlyph(b);
        const k = font.getKerningValue(ga, gb);
        if (k) kern[a + b] = Math.round(k);
      }
    }

    out.faces[face.id] = {
      label: face.label,
      unitsPerEm: upm,
      ascender: font.ascender,
      descender: font.descender,
      capHeight: font.tables.os2?.sCapHeight ?? null,
      xHeight: font.tables.os2?.sxHeight ?? null,
      glyphs,
      kern,
    };

    console.log(
      `✓ ${face.id.padEnd(13)} ${present.length} glyphs, ${Object.keys(kern).length} kern pairs`
    );
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(out));
  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`\nWrote ${path.relative(process.cwd(), OUT)} (${kb} KB)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
